// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hms.DataAccess;

namespace hms.DataAccess.Migrations
{
    [DbContext(typeof(hmsDbContext))]
    partial class hmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("hms.DataModel.HP_CHECKUP", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BODY_TEMPERATURE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BP_DOWN")
                        .HasColumnType("int");

                    b.Property<int>("BP_UP")
                        .HasColumnType("int");

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("HEIGHT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("PATIENT_AGE")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("PATIENT_CONTACT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PATIENT_SEX")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("PRESCRIPTION_NUMBER")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("WEIGHT")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("HP_CHECKUP");
                });

            modelBuilder.Entity("hms.DataModel.HP_DURATION", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DURATION_NAME")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("HP_DURATION");
                });

            modelBuilder.Entity("hms.DataModel.HP_FREQUENCY", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FREQUENCY_NAME")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("HP_FREQUENCY");
                });

            modelBuilder.Entity("hms.DataModel.HP_INVESTIGATION", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("HS_ITEM_ID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<long>("ITEM_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("ITEM_NAME")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("PRESCRIPTION_NUMBER")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SUGGESTION")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("HS_ITEM_ID");

                    b.ToTable("HP_INVESTIGATION");
                });

            modelBuilder.Entity("hms.DataModel.HP_MEDICINE", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DOSAGE_DURATION")
                        .HasColumnType("int");

                    b.Property<string>("DOSAGE_FREQUENCY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<long>("ITEM_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("ITEM_NAME")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("PRESCRIPTION_NUMBER")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SUGGESTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("HP_MEDICINE");
                });

            modelBuilder.Entity("hms.DataModel.HP_PRESCRIPTION", b =>
                {
                    b.Property<long>("PRESCRIPTION_NUMBER")
                        .HasColumnType("bigint");

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DOCTOR_ID")
                        .HasMaxLength(6)
                        .HasColumnType("int");

                    b.Property<int>("HOSPITAL_ID")
                        .HasMaxLength(6)
                        .HasColumnType("int");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<long>("PATIENT_ID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PRESCRIPTION_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("PREVIOUS_PRESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("REFER_FOR_ADMIT")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SHOW_TYPE_ID")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<long>("TOKEN_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PRESCRIPTION_NUMBER");

                    b.ToTable("HP_PRESCRIPTION");
                });

            modelBuilder.Entity("hms.DataModel.HP_SHOW_TYPE", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SHOW_NAME")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("HP_SHOW_TYPE");
                });

            modelBuilder.Entity("hms.DataModel.HP_SUGGESSION", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SUGGESTION_NAME")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("HP_SUGGESSION");
                });

            modelBuilder.Entity("hms.DataModel.HP_TOKEN", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DOCTOR_ID")
                        .HasColumnType("int");

                    b.Property<int?>("HS_DOCTOR_ID")
                        .HasColumnType("int");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SERIAL_NO")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<DateTime>("TOKEN_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("HS_DOCTOR_ID");

                    b.ToTable("HP_TOKEN");
                });

            modelBuilder.Entity("hms.DataModel.HS_DOCTOR", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DOCTOR_NAME")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("HS_DOCTOR");
                });

            modelBuilder.Entity("hms.DataModel.HS_HOSPITAL", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HOSPITAL_NAME")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("HS_HOSPITAL");
                });

            modelBuilder.Entity("hms.DataModel.HS_ITEM", b =>
                {
                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("ITEM_NAME")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("HS_ITEM");
                });

            modelBuilder.Entity("hms.DataModel.HS_PATIENT", b =>
                {
                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DATE_OF_BIRTH")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("PATIENT_NAME")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("HS_PATIENT");
                });

            modelBuilder.Entity("hms.DataModel.HS_TESTS", b =>
                {
                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TESTS_NAME")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("HS_TESTS");
                });

            modelBuilder.Entity("hms.DataModel.US_BLOOD_GROUP", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("BLOOD_GROUP_NAME")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("US_BLOOD_GROUP");
                });

            modelBuilder.Entity("hms.DataModel.US_CHILD_MENU", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("ACTION_NAME")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("AREA_NAME")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CHILD_BN_NAME")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CHILD_ICON")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CHILD_NAME")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CONTROLLER_NAME")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("US_MODULE_ID")
                        .HasColumnType("int");

                    b.Property<int>("US_PARENT_MENU_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("US_MODULE_ID");

                    b.HasIndex("US_PARENT_MENU_ID");

                    b.ToTable("US_CHILD_MENU");
                });

            modelBuilder.Entity("hms.DataModel.US_GENDER", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GENDER_NAME")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("US_GENDER");
                });

            modelBuilder.Entity("hms.DataModel.US_MARITAIL_STATUS", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("MARITAIL_STATUS_NAME")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("US_MARITAIL_STATUS");
                });

            modelBuilder.Entity("hms.DataModel.US_MODULE", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("CONTROLLER_NAME")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("METHOD_NAME")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MODULE_BN_NAME")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MODULE_ICON")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MODULE_NAME")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VIEW_ORDER")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("US_MODULE");
                });

            modelBuilder.Entity("hms.DataModel.US_PARENT_MENU", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("PARENT_BN_NAME")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PARENT_ICON")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PARENT_NAME")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("US_PARENT_MENU");
                });

            modelBuilder.Entity("hms.DataModel.US_RELIGION", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("RELIGION_NAME")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("US_RELIGION");
                });

            modelBuilder.Entity("hms.DataModel.US_ROLE", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("ROLE_NAME")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("US_ROLE");
                });

            modelBuilder.Entity("hms.DataModel.US_ROLE_MENU", b =>
                {
                    b.Property<int>("US_ROLE_ID")
                        .HasColumnType("int");

                    b.Property<int>("US_CHILD_MENU_ID")
                        .HasColumnType("int");

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("US_ROLE_ID", "US_CHILD_MENU_ID")
                        .HasName("PK_US_ROLE_MENU_ID");

                    b.HasIndex("US_CHILD_MENU_ID");

                    b.ToTable("US_ROLE_MENU");
                });

            modelBuilder.Entity("hms.DataModel.US_TYPE", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TYPE_NAME")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("US_TYPE");
                });

            modelBuilder.Entity("hms.DataModel.US_USER", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DATE_OF_BIRTH")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMAIL_ID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("LOGIN_ID")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MOBILE_NO")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PASSWORD")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PROFILE_IMAGE")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("USER_NAME")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("US_BLOOD_GROUP_ID")
                        .HasColumnType("int");

                    b.Property<int>("US_GENDER_ID")
                        .HasColumnType("int");

                    b.Property<int>("US_MARITAIL_STATUS_ID")
                        .HasColumnType("int");

                    b.Property<int>("US_RELIGION_ID")
                        .HasColumnType("int");

                    b.Property<int>("US_TYPE_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("US_BLOOD_GROUP_ID");

                    b.HasIndex("US_GENDER_ID");

                    b.HasIndex("US_MARITAIL_STATUS_ID");

                    b.HasIndex("US_RELIGION_ID");

                    b.HasIndex("US_TYPE_ID");

                    b.ToTable("US_USER");
                });

            modelBuilder.Entity("hms.DataModel.US_USER_ROLE", b =>
                {
                    b.Property<int>("US_USER_ID")
                        .HasColumnType("int");

                    b.Property<int>("US_ROLE_ID")
                        .HasColumnType("int");

                    b.Property<string>("CREATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UPDATE_BY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_DEVICE")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("US_USER_ID", "US_ROLE_ID")
                        .HasName("PK_US_USER_ROLE_ID");

                    b.HasIndex("US_ROLE_ID");

                    b.ToTable("US_USER_ROLE");
                });

            modelBuilder.Entity("hms.DataModel.HP_INVESTIGATION", b =>
                {
                    b.HasOne("hms.DataModel.HS_ITEM", "HS_ITEM")
                        .WithMany()
                        .HasForeignKey("HS_ITEM_ID");

                    b.Navigation("HS_ITEM");
                });

            modelBuilder.Entity("hms.DataModel.HP_TOKEN", b =>
                {
                    b.HasOne("hms.DataModel.HS_DOCTOR", "HS_DOCTOR")
                        .WithMany()
                        .HasForeignKey("HS_DOCTOR_ID");

                    b.Navigation("HS_DOCTOR");
                });

            modelBuilder.Entity("hms.DataModel.US_CHILD_MENU", b =>
                {
                    b.HasOne("hms.DataModel.US_MODULE", "US_MODULE")
                        .WithMany()
                        .HasForeignKey("US_MODULE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hms.DataModel.US_PARENT_MENU", "US_PARENT_MENU")
                        .WithMany()
                        .HasForeignKey("US_PARENT_MENU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("US_MODULE");

                    b.Navigation("US_PARENT_MENU");
                });

            modelBuilder.Entity("hms.DataModel.US_ROLE_MENU", b =>
                {
                    b.HasOne("hms.DataModel.US_CHILD_MENU", "US_CHILD_MENU")
                        .WithMany()
                        .HasForeignKey("US_CHILD_MENU_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hms.DataModel.US_ROLE", "US_ROLE")
                        .WithMany()
                        .HasForeignKey("US_ROLE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("US_CHILD_MENU");

                    b.Navigation("US_ROLE");
                });

            modelBuilder.Entity("hms.DataModel.US_USER", b =>
                {
                    b.HasOne("hms.DataModel.US_BLOOD_GROUP", "US_BLOOD_GROUP")
                        .WithMany()
                        .HasForeignKey("US_BLOOD_GROUP_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hms.DataModel.US_GENDER", "US_GENDER")
                        .WithMany()
                        .HasForeignKey("US_GENDER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hms.DataModel.US_MARITAIL_STATUS", "US_MARITAIL_STATUS")
                        .WithMany()
                        .HasForeignKey("US_MARITAIL_STATUS_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hms.DataModel.US_RELIGION", "US_RELIGION")
                        .WithMany()
                        .HasForeignKey("US_RELIGION_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hms.DataModel.US_TYPE", "US_TYPE")
                        .WithMany()
                        .HasForeignKey("US_TYPE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("US_BLOOD_GROUP");

                    b.Navigation("US_GENDER");

                    b.Navigation("US_MARITAIL_STATUS");

                    b.Navigation("US_RELIGION");

                    b.Navigation("US_TYPE");
                });

            modelBuilder.Entity("hms.DataModel.US_USER_ROLE", b =>
                {
                    b.HasOne("hms.DataModel.US_ROLE", "US_ROLE")
                        .WithMany()
                        .HasForeignKey("US_ROLE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hms.DataModel.US_USER", "US_USER")
                        .WithMany()
                        .HasForeignKey("US_USER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("US_ROLE");

                    b.Navigation("US_USER");
                });
#pragma warning restore 612, 618
        }
    }
}
